# Generated by Django 2.1.2 on 2018-11-27 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomies', '0003_auto_20181109_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryStats',
            fields=[
                ('patient_id', models.BigIntegerField()),
                ('code_id', models.BigIntegerField()),
                ('kind', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=4096)),
                ('count', models.IntegerField()),
                ('earliest', models.DateField()),
                ('latest', models.DateField()),
            ],
            options={
                'db_table': 'v_patient_history_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doc_type', models.CharField(max_length=8)),
                ('sub_type', models.CharField(max_length=128)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CPTInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomies.CPT')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ICDInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomies.ICD')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('unit', models.CharField(max_length=32)),
                ('value', models.FloatField(default=0)),
                ('normal_min', models.FloatField(null=True)),
                ('normal_max', models.FloatField(null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomies.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=64)),
                ('strength', models.CharField(max_length=64)),
                ('route', models.CharField(max_length=64)),
                ('frequency', models.CharField(max_length=64)),
                ('dose', models.CharField(max_length=64, null=True)),
                ('duration', models.CharField(max_length=64, null=True)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32)),
                ('last_name', models.CharField(max_length=128)),
                ('mrn', models.CharField(max_length=32, unique=True)),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('birthdate', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('other', 'other or N/A')], max_length=16, null=True)),
                ('is_sample', models.BooleanField()),
                ('cpts', models.ManyToManyField(through='patients.CPTInstance', to='taxonomies.CPT')),
                ('icds', models.ManyToManyField(through='patients.ICDInstance', to='taxonomies.ICD')),
                ('labs', models.ManyToManyField(through='patients.LabInstance', to='taxonomies.Lab')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meds', to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='labinstance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='icdinstance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='cptinstance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='patients.Patient'),
        ),
    ]
