# Generated by Django 2.1.2 on 2018-12-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinstance',
            name='perc_10',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='labinstance',
            name='perc_25',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='labinstance',
            name='perc_75',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='labinstance',
            name='perc_90',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='labinstance',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
