# Generated by Django 2.1.2 on 2019-01-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20181222_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='strength_num',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
