# Generated by Django 2.1.2 on 2019-01-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20190107_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinstance',
            name='perc_50',
            field=models.FloatField(null=True),
        ),
    ]
