# Generated by Django 2.1.2 on 2019-01-15 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_labinstance_perc_50'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField()),
                ('value', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('status_code', models.IntegerField()),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals_bp', to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('weight_date', models.DateTimeField()),
                ('height', models.FloatField()),
                ('height_date', models.DateTimeField()),
                ('bmi', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals_bmi', to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField()),
                ('name', models.CharField(max_length=32)),
                ('value', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals_hr', to='patients.Patient')),
            ],
        ),
    ]
