# Generated by Django 2.1.2 on 2019-01-15 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_bloodpressure_bmi_heartrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weight',
        ),
    ]
