# Generated by Django 2.1.2 on 2019-01-09 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomies', '0004_auto_20181217_2346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0004_labinstance_perc_50'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionTabSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField(default=0.75)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomies.Phecode')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
