# Generated by Django 2.1.2 on 2019-01-09 22:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomies', '0004_auto_20181217_2346'),
        ('patients', '0004_labinstance_perc_50'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conditiontabspec',
            unique_together={('user', 'patient', 'condition')},
        ),
    ]
