# Generated by Django 2.1.2 on 2018-10-17 19:58
# But hand written to generate a view
from django.db import migrations

# Each block below is similar but subtly different from the others in ways that
# are hard to parameterize.  The ICD block excludes codes with no chapter /
# phecode from consideration, the labs convert datetimes to dates, etc.
CREATE = """
CREATE MATERIALIZED VIEW v_patient_history_stats
AS SELECT * FROM (
    (
        SELECT
            B.patient_id,
            A.id AS "code_id",
            'icd' AS "kind",
            A.code,
            A.description,
            COUNT(A.code) AS "count",
            (
                SELECT MIN(date)
                FROM patients_icdinstance U
                WHERE U.patient_id = B.patient_id AND U.code_id = A.id
            ) AS earliest,
            (
                SELECT MAX(date)
                FROM patients_icdinstance U
                WHERE U.patient_id = B.patient_id AND U.code_id = A.id
            ) AS latest
        FROM
            taxonomies_icd A
            INNER JOIN patients_icdinstance B
            ON A.id = B.code_id
        GROUP BY
            B.patient_id,
            A.id
        HAVING
            A.phecode_id IS NOT NULL AND
            A.chapter_id IS NOT NULL
    )
    UNION
    (
        SELECT
            B.patient_id,
            A.id AS "code_id",
            'cpt' AS "kind",
            A.code,
            A.description,
            COUNT(A.code) AS "count",
            (
                SELECT MIN(date)
                FROM patients_cptinstance U
                WHERE U.patient_id = B.patient_id AND U.code_id = A.id
            ) AS earliest,
            (
                SELECT MAX(date)
                FROM patients_cptinstance U
                WHERE U.patient_id = B.patient_id AND U.code_id = A.id
            ) AS latest
        FROM
            taxonomies_cpt A
            INNER JOIN patients_cptinstance B
            ON A.id = B.code_id
        GROUP BY
            B.patient_id,
            A.id
    )
    UNION
    (
        SELECT
            B.patient_id,
            A.id AS "code_id",
            'lab' AS "kind",
            A.code,
            A.description,
            COUNT(A.code) AS "count",
            (
                SELECT MIN(datetime)::date
                FROM patients_labinstance U
                WHERE U.patient_id = B.patient_id AND U.code_id = A.id
            ) AS earliest,
            (
                SELECT MAX(datetime)::date
                FROM patients_labinstance U
                WHERE U.patient_id = B.patient_id AND U.code_id = A.id
            ) AS latest
        FROM
            taxonomies_lab A
            INNER JOIN patients_labinstance B
            ON A.id = B.code_id
        GROUP BY
            B.patient_id,
            A.id
    )
    UNION
    (
        SELECT
            A.patient_id,
            NULL AS "code_id",
            'med' AS "kind",
            A.name AS "code",
            A.description,
            COUNT(*) as "count",
            (
                SELECT MIN(date)
                FROM patients_medication M
                WHERE
                (
                    M.patient_id = A.patient_id AND
                    M.name = A.name AND
                    M.description = A.description
                )
            ) AS earliest,
            (
                SELECT MAX(date)
                FROM patients_medication M
                WHERE
                (
                    M.patient_id = A.patient_id AND
                    M.name = A.name AND
                    M.description = A.description
                )
            ) AS latest
        FROM patients_medication A
        GROUP BY A.patient_id, A.name, A.description
    )
) AS ALL_CODES;
"""

DROP = """
DROP MATERIALIZED VIEW IF EXISTS v_patient_history_stats;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(CREATE, DROP)
    ]
