# Common configuration
version: '3.7'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data:
  # Maintains shell history across runs when using the interactive shell to
  # inspect / work with the database
  ipython-history:
