# Staging (inferno) configuration
version: '3.7'

services:
  app:
    build: .
    command: ["/run-app"]
    ports:
      - "8080:8080"
    volumes:
      - ipython-history:/root/.ipython/profile_default
    depends_on:
      - db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
