# Generated by Django 2.1.2 on 2018-10-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(default='', max_length=4096)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
