# Generated by Django 2.1.2 on 2018-11-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0002_cpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpt',
            name='category',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='cpt',
            name='subcategory',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
