# Generated by Django 2.1.2 on 2018-12-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0003_auto_20181109_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icd',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
